### ISSUE TITLE
Failure with Swift Package Manager

### ISSUE THREAD

**Issue by robbiehanson** [kiliankoe/CircularCheckmarkProgress#4]
This is the error I get when I attempt to add it to a project using Swift Package Manager:

<img width="743" alt="Screen Shot 2021-07-28 at 15 36 20" src="https://user-images.githubusercontent.com/304604/127392412-fe36aa81-4c95-4060-9685-edc38b5531fa.png">

I'm using Xcode v12.5.1 (12E507)

**Comment by kiliankoe** [comment]
Hey @robbiehanson! Fun to see that this just randomly starts failing 🙈 I just fixed the manifest and pushed a new version (0.4.1). Thanks for the issue!

**Comment by robbiehanson** [comment]
> Fun to see that this just randomly starts failing

That's exactly what I thought! I thought the whole point of the `// swift-tools-version:<specifier>` was so that Xcode could prevent these types of bugs. :man_facepalming:

Thanks for the fix!

**Comment by kiliankoe** [comment]
Yeah I thought the same! But I guess/hope there's a reason 😅 

Huge thanks for the PayPal btw!
